-- AlterTable
ALTER TABLE `BoardingPass` ADD COLUMN `status` ENUM('PENDING', 'BOARDED', 'EXPIRED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `Payment` MODIFY `createdAt` DECIMAL(20, 3) NOT NULL DEFAULT (UNIX_TIMESTAMP()*1000),
    MODIFY `updatedAt` DECIMAL(20, 3) NOT NULL DEFAULT (UNIX_TIMESTAMP()*1000);
