-- AlterTable
ALTER TABLE `User` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `firstname` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `lastname` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `pictureUrl` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `rank` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `role` ENUM('USER', 'ADMIN', 'MONITOR') NOT NULL DEFAULT 'USER';
