import { PartialType } from '@nestjs/swagger';
import { IsEmail, IsNotEmpty, Matches, MinLength } from 'class-validator';
enum Role {
  ADMIN = 'admin',
  USER = 'user',
}
export class RegisterDto {
  @IsNotEmpty()
  id?: number; // Optional for registration, will be generated by the database
  @IsNotEmpty()
  @IsEmail()
  email: string;
  @MinLength(8)
  password: string;
  @IsNotEmpty()
  firstName: string;
  @IsNotEmpty()
  lastName: string;
  @Matches(/^\+\d{1,3}\d{9,15}$/)
  phoneNumber: string;
  dateOfBirth: Date;
  role: string; // e.g., 'admin', 'user', etc.
}
