-- AlterTable
ALTER TABLE `User` ADD COLUMN `accountLockYn` VARCHAR(191) NOT NULL DEFAULT 'N',
    ADD COLUMN `authType` VARCHAR(191) NOT NULL DEFAULT 'ID,PW',
    ADD COLUMN `loginFailCnt` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `mfaEnabledYn` VARCHAR(191) NOT NULL DEFAULT 'N',
    ADD COLUMN `mfaSecretKey` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `prevPassword` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `userAlias` VARCHAR(191) NOT NULL DEFAULT '';
