-- AlterTable
ALTER TABLE `Passenger` ADD COLUMN `otpCode` VARCHAR(191) NULL,
    ADD COLUMN `otpExpire` DECIMAL(20, 3) NULL,
    ADD COLUMN `role` ENUM('PASSENGER', 'USER', 'ADMIN', 'MONITOR') NOT NULL DEFAULT 'PASSENGER';

-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('PASSENGER', 'USER', 'ADMIN', 'MONITOR') NOT NULL DEFAULT 'USER';
