-- AlterTable
ALTER TABLE `User` ADD COLUMN `approvalTransferAdminDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `approvalTransferAdminYn` VARCHAR(191) NOT NULL DEFAULT 'N',
    ADD COLUMN `fromTransferAdminUserId` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `fromTransferAdminUserYn` VARCHAR(191) NOT NULL DEFAULT 'N',
    ADD COLUMN `lastLoginDate` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `requestTransferAdminDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `toTransferAdminUserId` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `touTransferAdminUserYn` VARCHAR(191) NOT NULL DEFAULT 'N';
