-- AlterTable
ALTER TABLE `Seat` ADD COLUMN `isExitRow` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `isExtraLegroom` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `note` VARCHAR(191) NULL,
    ADD COLUMN `position` ENUM('WINDOW', 'MIDDLE', 'AISLE') NULL,
    ADD COLUMN `price` DOUBLE NULL,
    MODIFY `type` ENUM('VIP', 'BUSINESS', 'ECONOMY', 'FIRST') NOT NULL DEFAULT 'ECONOMY',
    MODIFY `isAvailable` BOOLEAN NULL DEFAULT true;
